# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20170422_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
