# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20170422_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='track',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
