# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20170423_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='comment',
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Track'),
        ),
    ]
