# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20170429_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='status',
            field=models.CharField(choices=[('q', 'Queried'), ('p', 'Playing')], default='q', max_length=1),
            preserve_default=False,
        ),
    ]
